version: '3.8'
networks:
  network1:
    name: testmysql_default
services:
  mysql-container:
    container_name: mysqldb
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: yahya
      MYSQL_PASSWORD: yahya

    networks:
      - network1
